version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "core-v-verif"
    labels:
      - "Component:Verif"
