name: Verible
on:
  pull_request_target:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: cathales/verible-formatter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: 'core/**/*.{v,sv}'
          fail_on_formatting_suggestions: true
